export enum STATUS {
    ATIVO = 'A',
    INATIVO = 'I',
}

export enum STATUS_FINANCEIRO {
    REGULAR = 'R',
    EM_DEBITO = 'E',
    CANCELADO = 'C',
}

export enum REGRA_USUARIO {
    ADMINISTRADOR = 'ADM',
    FUNCIONARIO = 'FUN',
    SUPERVISOR = 'SUP',
    COORDENADOR = 'COO'
}

export enum TIPO_REGISTRO {
    PRESENCIAL = 'PRE',
    REMOTO = 'REM',
    HIBRIDO = 'HIB',
}

export enum TIPO_AUSENCIA {
    FERIADO = 'FER',
    AUSENTE = 'AUS',
    FOLGA = 'FOL',
    ATESTADO = 'ATE',
    OUTROS = 'OUT'
}

export enum TIPO_BENEFICIO {
    PLANO_SAUDE = 'PLSD',
    PLANO_ODONTOLOGICO = 'PLOG',
    PLANO_TERAPEUTICO = 'PLTC',
    AUXILIO_MEDICO = 'AUMD',
    AUXILIO_EDUCACAO = 'AUED',
    AUXILIO_FINANCEIRO = 'AUFN',
    VALE_ALIMENTACAO = 'VAAT',
    VALE_TRANSPORTE = 'VTRN',
    VALE_COMBUSTIVEL = 'VCBT',
    OUTROS = 'OUT'
}

export enum TIPO_DESCONTO {
    INSS = 'INSS',
    IRRF = 'IRRF',
    ADIANTAMENTO = 'ADMT',
    EMPRESTIMO = 'EMPT',
    PLANO_SAUDE = 'PLSD',
    PLANO_ODONTOLOGICO = 'PLOG',
    PLANO_TERAPEUTICO = 'PLTC',
    AUXILIO_MEDICO = 'AUMD',
    AUXILIO_EDUCACAO = 'AUED',
    AUXILIO_FINANCEIRO = 'AUFN',
    VALE_ALIMENTACAO = 'VAAT',
    VALE_TRANSPORTE = 'VTRN',
    VALE_COMBUSTIVEL = 'VCBT',
    OUT = 'OUT'
}