import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1734181766589 implements MigrationInterface {
    name = 'Default1734181766589'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "TENANTS" ("ID" SERIAL NOT NULL, "RAZAO" character varying(150) NOT NULL, "CPFCNPJ" character varying(20) NOT NULL, "EMAIL" character varying(150) NOT NULL, "ENDERECO" character varying(200), "CIDADE" character varying(100), "ESTADO" character varying(2), "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, CONSTRAINT "PK_3e9470aa638d03c4d8f4dd4c3d5" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TYPE "public"."FERIADOS_AUSENCIAS_tipo_enum" AS ENUM('FER', 'AUS', 'FOL', 'ATE', 'OUT')`);
        await queryRunner.query(`CREATE TABLE "FERIADOS_AUSENCIAS" ("ID" SERIAL NOT NULL, "DATA_INICIO" TIMESTAMP NOT NULL, "DATA_FIM" TIMESTAMP NOT NULL, "TIPO" "public"."FERIADOS_AUSENCIAS_tipo_enum" NOT NULL DEFAULT 'OUT', "JUSTIFICATIVA" text, "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "FUNCIONARIO_ID" integer NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_abb4cdfc8515ceca1b4e0ec76dd" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "HORAS_EXTRAS" ("ID" SERIAL NOT NULL, "DATA" TIMESTAMP NOT NULL, "APROVADO" boolean NOT NULL DEFAULT false, "MOTIVO" text, "QUANTIDADE_HORAS" integer NOT NULL, "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "FUNCIONARIO_ID" integer NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_a8de0fbf0822adaf48e4cb3d222" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TYPE "public"."REGISTROS_PRONTOS_tipo_regisro_enum" AS ENUM('PRE', 'REM', 'HIB')`);
        await queryRunner.query(`CREATE TABLE "REGISTROS_PRONTOS" ("ID" SERIAL NOT NULL, "DATA" TIMESTAMP NOT NULL, "HORA_ENTRADA" TIME NOT NULL, "HORA_SAIDA" TIME NOT NULL, "HORA_ALMOCO_INICIO" TIME NOT NULL, "HORA_ALMOCO_FIM" TIME NOT NULL, "TIPO_REGISRO" "public"."REGISTROS_PRONTOS_tipo_regisro_enum" NOT NULL DEFAULT 'PRE', "OBSERVACOES" character varying(200) NOT NULL, "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "FUNCIONARIO_ID" integer NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_9302c42b7e4234f7bfbc7c768c4" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TYPE "public"."FUNCIONARIOS_status_enum" AS ENUM('A', 'I')`);
        await queryRunner.query(`CREATE TYPE "public"."FUNCIONARIOS_regra_enum" AS ENUM('ADM', 'FUN', 'SUP', 'COO')`);
        await queryRunner.query(`CREATE TABLE "FUNCIONARIOS" ("ID" SERIAL NOT NULL, "NOME" character varying(150) NOT NULL, "CPF" character varying(20) NOT NULL, "STATUS" "public"."FUNCIONARIOS_status_enum" NOT NULL DEFAULT 'A', "REGRA" "public"."FUNCIONARIOS_regra_enum" NOT NULL DEFAULT 'FUN', "EMAIL" character varying(150) NOT NULL, "SENHA" character varying(100) NOT NULL, "ENDERECO" character varying(200) NOT NULL, "TELEFONE" character varying(20) NOT NULL, "SEXO" character varying(1) NOT NULL, "ESTADO_CIVIL" character varying(1) NOT NULL, "DATA_ADMISSAO" TIMESTAMP, "DATA_NASCIMENTO" TIMESTAMP, "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "PROFISSAO_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, "EMPRESA_ID" integer NOT NULL, CONSTRAINT "PK_5f148007c782d3f26363295856f" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TYPE "public"."EMPRESAS_status_enum" AS ENUM('A', 'I')`);
        await queryRunner.query(`CREATE TABLE "EMPRESAS" ("ID" SERIAL NOT NULL, "NOME_FANTASIA" character varying(150) NOT NULL, "RAZAO_SOCIAL" character varying(150) NOT NULL, "CNPJ" character varying(20) NOT NULL, "STATUS" "public"."EMPRESAS_status_enum" NOT NULL DEFAULT 'A', "ENDERECO" character varying(150), "CIDADE" character varying(100), "ESTADO" character varying(2), "CELULAR" character varying(20), "EMAIL" character varying(100), "LOGO" text, "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_4a6f6e63ea5c6a853488fb5e392" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "JORNADAS_TRABALHOS" ("ID" SERIAL NOT NULL, "DIAS_SEMANAS" text NOT NULL, "HORA_INICIO" TIME NOT NULL, "HORA_FIM" TIME NOT NULL, "INTERVALO" TIME NOT NULL, "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_61e264ecf13aca0f373a53e48b9" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "PROFISSOES" ("ID" SERIAL NOT NULL, "NOME" character varying(100) NOT NULL, "DESCRICAO" text, "SALARIO_BASE" numeric(10,2) NOT NULL DEFAULT '0', "TOTAL_BENEFICIOS" numeric(10,2) NOT NULL DEFAULT '0', "TOTAL_DESCONTOS" numeric(10,2) NOT NULL DEFAULT '0', "ADICIONAL_PADRAO" numeric(10,2) NOT NULL DEFAULT '0', "ADICIONAL_NOTURNO" numeric(10,2) NOT NULL DEFAULT '0', "VALOR_HORA_EXTRA" numeric(10,2) NOT NULL DEFAULT '0', "DATA_CRIACAO" TIMESTAMP NOT NULL DEFAULT now(), "DATA_ATUALIZACAO" TIMESTAMP, "JORNADA_ID" integer NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_1b3c5dc00768871e18ba07eb319" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "FOLHA_PAGAMENTOS" ("ID" SERIAL NOT NULL, "DATA_PAGAMENTO" TIMESTAMP NOT NULL, "MES_REFERENCIA" character varying(50) NOT NULL, "SALARIO_BRUTO" numeric(10,2) NOT NULL, "SALARIO_LIQUIDO" numeric(10,2) NOT NULL, "FUNCIONARIO_ID" integer NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_d05fca0148693711743194dcdd1" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TYPE "public"."DESCONTOS_tipo_enum" AS ENUM('PLSD', 'PLOG', 'PLTC', 'AUMD', 'AUED', 'AUFN', 'VAAT', 'VTRN', 'VCBT', 'OUT')`);
        await queryRunner.query(`CREATE TABLE "DESCONTOS" ("ID" SERIAL NOT NULL, "TIPO" "public"."DESCONTOS_tipo_enum" NOT NULL DEFAULT 'OUT', "DESCRICAO" character varying(150), "ALTERAR_SALARIO" boolean NOT NULL DEFAULT false, "VALOR" numeric(10,2) NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_87d2b245c4d9feed5f2fa59cc24" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TYPE "public"."BENEFICIOS_tipo_enum" AS ENUM('PLSD', 'PLOG', 'PLTC', 'AUMD', 'AUED', 'AUFN', 'VAAT', 'VTRN', 'VCBT', 'OUT')`);
        await queryRunner.query(`CREATE TABLE "BENEFICIOS" ("ID" SERIAL NOT NULL, "TIPO" "public"."BENEFICIOS_tipo_enum" NOT NULL DEFAULT 'OUT', "DESCRICAO" character varying(150), "ALTERAR_SALARIO" boolean NOT NULL DEFAULT false, "VALOR" numeric(10,2) NOT NULL, "EMPRESA_ID" integer NOT NULL, "TENANT_ID" integer NOT NULL, CONSTRAINT "PK_3105d02c231b9b36c7bf301518f" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`ALTER TABLE "FERIADOS_AUSENCIAS" ADD CONSTRAINT "FK_5558fc5364d4fa11712e6ffc030" FOREIGN KEY ("FUNCIONARIO_ID") REFERENCES "FUNCIONARIOS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FERIADOS_AUSENCIAS" ADD CONSTRAINT "FK_5ddd1fe9b1b4185939a4e8a9921" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FERIADOS_AUSENCIAS" ADD CONSTRAINT "FK_bc84b740e96ea2649b01aa78227" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "HORAS_EXTRAS" ADD CONSTRAINT "FK_acb48ea06423ac5fabfe2d02c0b" FOREIGN KEY ("FUNCIONARIO_ID") REFERENCES "FUNCIONARIOS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "HORAS_EXTRAS" ADD CONSTRAINT "FK_d4260f32dcab55302d696fdf5c3" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "HORAS_EXTRAS" ADD CONSTRAINT "FK_5cb2b56955c4f05601f60a6916c" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "REGISTROS_PRONTOS" ADD CONSTRAINT "FK_567453257a9268b9b9e58ace023" FOREIGN KEY ("FUNCIONARIO_ID") REFERENCES "FUNCIONARIOS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "REGISTROS_PRONTOS" ADD CONSTRAINT "FK_d69a98a6ac94bff6b683418ac75" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "REGISTROS_PRONTOS" ADD CONSTRAINT "FK_194f3b413e4af73423bc431e6c2" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FUNCIONARIOS" ADD CONSTRAINT "FK_87eae97d506872b88ab4fb00073" FOREIGN KEY ("PROFISSAO_ID") REFERENCES "PROFISSOES"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FUNCIONARIOS" ADD CONSTRAINT "FK_78341b6bb527ebcb45fcae299cc" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FUNCIONARIOS" ADD CONSTRAINT "FK_85111fa70005f447956fadbcf5a" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EMPRESAS" ADD CONSTRAINT "FK_6388d871f3c30bb475552942025" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "JORNADAS_TRABALHOS" ADD CONSTRAINT "FK_d913e168b4ec813b3e40f66a016" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "JORNADAS_TRABALHOS" ADD CONSTRAINT "FK_d09c994e800d324d948265db06f" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PROFISSOES" ADD CONSTRAINT "FK_c20f45bce11835dc06cd357cf50" FOREIGN KEY ("JORNADA_ID") REFERENCES "JORNADAS_TRABALHOS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PROFISSOES" ADD CONSTRAINT "FK_82e695f234f53ec0ae6a53cd1e0" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PROFISSOES" ADD CONSTRAINT "FK_a7309b4e03032c3c67594473129" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FOLHA_PAGAMENTOS" ADD CONSTRAINT "FK_779646f46790f90bc234efff29e" FOREIGN KEY ("FUNCIONARIO_ID") REFERENCES "FUNCIONARIOS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FOLHA_PAGAMENTOS" ADD CONSTRAINT "FK_cf3cb27d85aad906540df06df2a" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FOLHA_PAGAMENTOS" ADD CONSTRAINT "FK_1ea895d754a923464c5d612d3da" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DESCONTOS" ADD CONSTRAINT "FK_5f1c2004157a77d685ebe6f1cff" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DESCONTOS" ADD CONSTRAINT "FK_0951e5a9d4236170ed9bd80f1f2" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "BENEFICIOS" ADD CONSTRAINT "FK_2563d62b7cffb4d90f5f34ebcb9" FOREIGN KEY ("EMPRESA_ID") REFERENCES "EMPRESAS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "BENEFICIOS" ADD CONSTRAINT "FK_99cb0ac8545966305164b94ba11" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "BENEFICIOS" DROP CONSTRAINT "FK_99cb0ac8545966305164b94ba11"`);
        await queryRunner.query(`ALTER TABLE "BENEFICIOS" DROP CONSTRAINT "FK_2563d62b7cffb4d90f5f34ebcb9"`);
        await queryRunner.query(`ALTER TABLE "DESCONTOS" DROP CONSTRAINT "FK_0951e5a9d4236170ed9bd80f1f2"`);
        await queryRunner.query(`ALTER TABLE "DESCONTOS" DROP CONSTRAINT "FK_5f1c2004157a77d685ebe6f1cff"`);
        await queryRunner.query(`ALTER TABLE "FOLHA_PAGAMENTOS" DROP CONSTRAINT "FK_1ea895d754a923464c5d612d3da"`);
        await queryRunner.query(`ALTER TABLE "FOLHA_PAGAMENTOS" DROP CONSTRAINT "FK_cf3cb27d85aad906540df06df2a"`);
        await queryRunner.query(`ALTER TABLE "FOLHA_PAGAMENTOS" DROP CONSTRAINT "FK_779646f46790f90bc234efff29e"`);
        await queryRunner.query(`ALTER TABLE "PROFISSOES" DROP CONSTRAINT "FK_a7309b4e03032c3c67594473129"`);
        await queryRunner.query(`ALTER TABLE "PROFISSOES" DROP CONSTRAINT "FK_82e695f234f53ec0ae6a53cd1e0"`);
        await queryRunner.query(`ALTER TABLE "PROFISSOES" DROP CONSTRAINT "FK_c20f45bce11835dc06cd357cf50"`);
        await queryRunner.query(`ALTER TABLE "JORNADAS_TRABALHOS" DROP CONSTRAINT "FK_d09c994e800d324d948265db06f"`);
        await queryRunner.query(`ALTER TABLE "JORNADAS_TRABALHOS" DROP CONSTRAINT "FK_d913e168b4ec813b3e40f66a016"`);
        await queryRunner.query(`ALTER TABLE "EMPRESAS" DROP CONSTRAINT "FK_6388d871f3c30bb475552942025"`);
        await queryRunner.query(`ALTER TABLE "FUNCIONARIOS" DROP CONSTRAINT "FK_85111fa70005f447956fadbcf5a"`);
        await queryRunner.query(`ALTER TABLE "FUNCIONARIOS" DROP CONSTRAINT "FK_78341b6bb527ebcb45fcae299cc"`);
        await queryRunner.query(`ALTER TABLE "FUNCIONARIOS" DROP CONSTRAINT "FK_87eae97d506872b88ab4fb00073"`);
        await queryRunner.query(`ALTER TABLE "REGISTROS_PRONTOS" DROP CONSTRAINT "FK_194f3b413e4af73423bc431e6c2"`);
        await queryRunner.query(`ALTER TABLE "REGISTROS_PRONTOS" DROP CONSTRAINT "FK_d69a98a6ac94bff6b683418ac75"`);
        await queryRunner.query(`ALTER TABLE "REGISTROS_PRONTOS" DROP CONSTRAINT "FK_567453257a9268b9b9e58ace023"`);
        await queryRunner.query(`ALTER TABLE "HORAS_EXTRAS" DROP CONSTRAINT "FK_5cb2b56955c4f05601f60a6916c"`);
        await queryRunner.query(`ALTER TABLE "HORAS_EXTRAS" DROP CONSTRAINT "FK_d4260f32dcab55302d696fdf5c3"`);
        await queryRunner.query(`ALTER TABLE "HORAS_EXTRAS" DROP CONSTRAINT "FK_acb48ea06423ac5fabfe2d02c0b"`);
        await queryRunner.query(`ALTER TABLE "FERIADOS_AUSENCIAS" DROP CONSTRAINT "FK_bc84b740e96ea2649b01aa78227"`);
        await queryRunner.query(`ALTER TABLE "FERIADOS_AUSENCIAS" DROP CONSTRAINT "FK_5ddd1fe9b1b4185939a4e8a9921"`);
        await queryRunner.query(`ALTER TABLE "FERIADOS_AUSENCIAS" DROP CONSTRAINT "FK_5558fc5364d4fa11712e6ffc030"`);
        await queryRunner.query(`DROP TABLE "BENEFICIOS"`);
        await queryRunner.query(`DROP TYPE "public"."BENEFICIOS_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "DESCONTOS"`);
        await queryRunner.query(`DROP TYPE "public"."DESCONTOS_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "FOLHA_PAGAMENTOS"`);
        await queryRunner.query(`DROP TABLE "PROFISSOES"`);
        await queryRunner.query(`DROP TABLE "JORNADAS_TRABALHOS"`);
        await queryRunner.query(`DROP TABLE "EMPRESAS"`);
        await queryRunner.query(`DROP TYPE "public"."EMPRESAS_status_enum"`);
        await queryRunner.query(`DROP TABLE "FUNCIONARIOS"`);
        await queryRunner.query(`DROP TYPE "public"."FUNCIONARIOS_regra_enum"`);
        await queryRunner.query(`DROP TYPE "public"."FUNCIONARIOS_status_enum"`);
        await queryRunner.query(`DROP TABLE "REGISTROS_PRONTOS"`);
        await queryRunner.query(`DROP TYPE "public"."REGISTROS_PRONTOS_tipo_regisro_enum"`);
        await queryRunner.query(`DROP TABLE "HORAS_EXTRAS"`);
        await queryRunner.query(`DROP TABLE "FERIADOS_AUSENCIAS"`);
        await queryRunner.query(`DROP TYPE "public"."FERIADOS_AUSENCIAS_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "TENANTS"`);
    }

}
